backend:
  name: git-gateway
  # name: test-repo
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Homepage - First section"
      name: "home"
      file: "content/home/index.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "string"}
        - { label: "Email", name: "email", widget: "string"}
        - label: "Links"
          name: "links"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
    - label: "Homepage - Bio section"
      name: "HomeBio"
      file: "content/home/bio.md"
      fields:
        - { label: "Content", name: "body", widget: "Markdown"}
    - label: "Homepage - Research section"
      name: "HomeResearch"
      file: "content/home/research.md"
      fields:
        - { label: "Content", name: "body", widget: "Markdown"}
    - label: "Homepage - Contacts section"
      name: "HomeContacts"
      file: "content/home/contacts.md"
      fields:
        - { label: "Content", name: "body", widget: "Markdown"}
    - label: "Research page"
      name: "Research"
      file: "content/home/index.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "string"}
        - { label: "Email", name: "email", widget: "string"}
        - label: "Links"
          name: "links"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
