backend:
  name: git-gateway
  # name: test-repo
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "homepage"
    label: "Home Page"
    files:
    - label: "Badge"
      name: "home-badge"
      file: "content/home/index.md"
      fields:
        - label: "Photo"
          name: "photo"
          widget: "image"
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Description"
          name: "description"
          widget: "string"
        - label: "Email"
          name: "email"
          widget: "string"
        - label: "Links"
          name: "links"
          widget: list
          fields:
            - label: "Name"
              name: "name"
              widget: "string"
            - label: "URL"
              name: "url"
              widget: "string"
    - label: "Bio"
      name: "home-bio"
      file: "content/home/bio.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
    - label: "Research"
      name: "home-research"
      file: "content/home/research.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
    - label: "Contacts"
      name: "home-contacts"
      file: "content/home/contacts.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
  - name: "research"
    label: "Research Page"
    files:
    - label: "Content"
      name: "research-content"
      file: "content/research.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
        - label: "Papers"
          name: "papers"
          widget: list
          fields:
            - label: "Title"
              name: "title"
              widget: "string"
            - label: "Author"
              name: "author"
              widget: "string"
            - label: "Journal"
              name: "journal"
              widget: "object"
              required: false
              fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
                  required: false
            - label: "Volume"
              name: "volume"
              widget: "string"
              required: false
            - label: "Pages"
              name: "pages"
              widget: "string"
              required: false
            - label: "Publisher"
              name: "publisher"
              required: false
              widget: "object"
              fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
                  required: false
            - label: "Year"
              name: "year"
              widget: "number"
            - label: "Links"
              name: "links"
              widget: list
              required: false
              fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "URL"
                  name: "url"
                  widget: "string"
  - name: "teaching"
    label: "Teaching Page"
    files:
    - label: "Content"
      name: "teaching-content"
      file: "content/teaching.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
          required: false
  - name: "seminars"
    label: "Seminars Page"
    files:
    - label: "Content"
      name: "seminars-content"
      file: "content/seminars.md"
      fields:
        - label: "Content"
          name: "body"
          widget: "markdown"
